# Generated by Django 5.2.17 on 2026-09-30 21:43

import django.db.models.deletion
import reportbuilder.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('resource_id', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('encrypted_secrets', models.TextField(blank=True)),
                ('upload', models.FileField(blank=True, upload_to=reportbuilder.models.upload_path)),
                ('allowed_objects', models.JSONField(blank=True, default=list)),
                ('allowed_columns', models.JSONField(blank=True, default=dict)),
                ('masks', models.JSONField(blank=True, default=dict)),
                ('row_policy', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='UNTESTED', max_length=20)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=reportbuilder.models.upload_path)),
                ('mime', models.CharField(default='image/png', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportbuilder.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.JSONField(default=dict)),
                ('bindings', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reportbuilder.project')),
                ('viewer_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('definition_snapshot', models.JSONField(default=dict)),
                ('datasets_snapshot', models.JSONField(default=dict)),
                ('bindings_snapshot', models.JSONField(default=list)),
                ('rendered_html', models.TextField(blank=True)),
                ('policy_fingerprint', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportbuilder.report')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('bindings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='reportbuilder.report')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='reportbuilder.report')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportbuilder.revision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('report', 'number'), name='report_revision_unique'),
        ),
    ]
