# Generated by Django 5.2.17 on 2026-10-02 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing(apps, schema_editor):
    Report = apps.get_model('reportbuilder', 'Report')
    DemoSeed = apps.get_model('reportbuilder', 'DemoSeed')
    database = schema_editor.connection.alias
    for owner_id in Report.objects.using(database).filter(name='매출 현황 예제').values_list('owner_id', flat=True).distinct():
        DemoSeed.objects.using(database).get_or_create(owner_id=owner_id, defaults={'completed': True})


class Migration(migrations.Migration):

    dependencies = [
        ('reportbuilder', '0003_reportaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(mark_existing, migrations.RunPython.noop),
    ]
