# Generated by Django 5.2.17 on 2026-10-02 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportbuilder', '0004_demoseed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_shares', to='reportbuilder.report')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportbuilder.revision')),
            ],
        ),
    ]
