# Generated by Django 5.2.17 on 2026-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportbuilder', '0005_publicshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicshare',
            name='public_window_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicshare',
            name='public_window_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
