# Generated by Django 5.2.17 on 2026-10-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportbuilder", "0007_googleoauthapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicshare",
            name="password_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="report",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_reports",
                to="reportbuilder.asset",
            ),
        ),
    ]
