# Generated by Django 5.2.17 on 2026-10-03 02:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportbuilder", "0008_publicshare_password_hash_report_cover"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="WebReportingBuilder",
                        max_length=120,
                        verbose_name="회사명",
                    ),
                ),
                ("logo", models.FileField(blank=True, upload_to="branding/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="게시판 이름")),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, verbose_name="설명"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("list", "리스트형"),
                            ("card", "카드형"),
                            ("qa", "질문답변형 (1:1)"),
                        ],
                        default="list",
                        max_length=8,
                        verbose_name="게시판 유형",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="사용")),
                (
                    "allow_user_posts",
                    models.BooleanField(
                        default=True, verbose_name="사용자 글쓰기 허용"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_boards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="게시판 관리자",
                    ),
                ),
                (
                    "operators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="operated_boards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="게시판 운영자",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="BoardCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="카테고리 이름")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="reportbuilder.board",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BoardPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("body", models.TextField(max_length=100000, verbose_name="내용")),
                (
                    "pinned",
                    models.BooleanField(default=False, verbose_name="상단 고정"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="reportbuilder.board",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reportbuilder.boardcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-pinned", "-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BoardReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "body",
                    models.TextField(max_length=100000, verbose_name="답변 / 댓글"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="reportbuilder.boardpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="BoardStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="상태 이름")),
                (
                    "color",
                    models.CharField(
                        default="#2563eb",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "색상은 #RRGGBB 형식이어야 합니다."
                            )
                        ],
                        verbose_name="색상",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="reportbuilder.board",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="boardpost",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reportbuilder.boardstatus",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcategory",
            constraint=models.UniqueConstraint(
                fields=("board", "name"), name="board_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardstatus",
            constraint=models.UniqueConstraint(
                fields=("board", "name"), name="board_status_name"
            ),
        ),
    ]
