# Generated by Django 5.2.17 on 2026-10-04 01:39

import django.db.models.deletion
from django.db import migrations, models


def seed_settings(apps, schema_editor):
    alias = schema_editor.connection.alias
    Section = apps.get_model('reportbuilder', 'SettingsSection')
    Menu = apps.get_model('reportbuilder', 'SettingsMenu')
    for key, label, order, child_key, child_label, url in (
        ('basic', '기본정보', 10, 'company', '회사로고', '/settings/company/'),
        ('site', '사이트관리', 20, 'menus', '메뉴관리', '/menu-management/'),
    ):
        section, _ = Section.objects.using(alias).get_or_create(
            key=key, defaults={'label': label, 'order': order, 'active': True})
        Menu.objects.using(alias).get_or_create(key=child_key, defaults={
            'section': section, 'label': child_label, 'url': url, 'order': 10, 'active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('reportbuilder', '0014_settings_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=40, verbose_name='탭명')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SettingsMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=40, verbose_name='하위 메뉴명')),
                ('url', models.CharField(max_length=255, verbose_name='내부 주소')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='reportbuilder.settingssection', verbose_name='중메뉴 탭')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_settings, migrations.RunPython.noop),
    ]
