# Generated by Django 5.2.17 on 2026-10-04 02:54

import uuid
from django.db import migrations, models


def seed_api_settings(apps, schema_editor):
    alias = schema_editor.connection.alias
    Section = apps.get_model('reportbuilder', 'SettingsSection')
    Menu = apps.get_model('reportbuilder', 'SettingsMenu')
    section, _ = Section.objects.using(alias).get_or_create(
        key='api', defaults={'label': 'API', 'order': 30, 'active': True})
    for key, label, url, order in (
        ('internal-api', '내부API', '/settings/api/internal/', 10),
        ('external-api', '외부API', '/settings/api/external/', 20),
    ):
        Menu.objects.using(alias).get_or_create(key=key, defaults={
            'section': section, 'label': label, 'url': url, 'order': order, 'active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('reportbuilder', '0016_infographics_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='연결명')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('compatible', 'OpenAI 호환 API')], max_length=20, verbose_name='제공자')),
                ('model', models.CharField(max_length=200, verbose_name='모델명')),
                ('base_url', models.URLField(max_length=500, verbose_name='API 기본 주소')),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RunPython(seed_api_settings, migrations.RunPython.noop),
    ]
