# Generated by Django 5.2.17 on 2026-10-04 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_user_llm_settings(apps, schema_editor):
    alias = schema_editor.connection.alias
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    owners = list(User.objects.using(alias).filter(is_staff=True).values_list('pk', flat=True)[:2])
    # The previous global settings did not record who created them. Do not
    # guess an owner when several administrators exist; retain encrypted rows.
    if len(owners) == 1:
        apps.get_model('reportbuilder', 'LLMConfiguration').objects.using(alias).filter(owner__isnull=True).update(owner_id=owners[0])
    apps.get_model('reportbuilder', 'SettingsSection').objects.using(alias).filter(key='api').update(staff_only=False)
    apps.get_model('reportbuilder', 'SettingsMenu').objects.using(alias).filter(key='external-api').update(staff_only=False)
    apps.get_model('reportbuilder', 'WorkspaceMenu').objects.using(alias).filter(key='settings').update(staff_only=False)


class Migration(migrations.Migration):

    dependencies = [
        ('reportbuilder', '0017_llmconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfiguration',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingsmenu',
            name='staff_only',
            field=models.BooleanField(default=True, verbose_name='관리자 전용'),
        ),
        migrations.AddField(
            model_name='settingssection',
            name='staff_only',
            field=models.BooleanField(default=True, verbose_name='관리자 전용'),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='name',
            field=models.CharField(max_length=120, verbose_name='연결명'),
        ),
        migrations.AddConstraint(
            model_name='llmconfiguration',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_user_llm_name'),
        ),
        migrations.RunPython(migrate_user_llm_settings, migrations.RunPython.noop),
    ]
