# Generated by Django 5.2.17 on 2026-10-04 13:30

from django.db import migrations, models


def add_mail_menu(apps, schema_editor):
    Section = apps.get_model('reportbuilder', 'SettingsSection')
    Menu = apps.get_model('reportbuilder', 'SettingsMenu')
    section, _ = Section.objects.using(schema_editor.connection.alias).get_or_create(
        key='basic', defaults={'label': '기본정보', 'order': 10, 'staff_only': True})
    Menu.objects.using(schema_editor.connection.alias).get_or_create(
        key='mail', defaults={'section': section, 'label': '메일', 'url': '/settings/mail/',
                              'order': 20, 'active': True, 'staff_only': True})


class Migration(migrations.Migration):

    dependencies = [
        ('reportbuilder', '0019_llmmodellookup'),
    ]

    operations = [
        migrations.RunPython(add_mail_menu, migrations.RunPython.noop),
        migrations.CreateModel(
            name='MailConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('options', models.JSONField(default=dict)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='mail_configuration_singleton')],
            },
        ),
    ]
