from django.urls import path
from . import views, google_oauth, sharing
from . import analytics_views
from . import branding, community, menu_views

urlpatterns = [
    path('settings/company/', branding.settings, name='company_settings'),
    path('menu-management/', menu_views.menu_management, name='menu_management'),
    path('company/logo/', branding.logo, name='company_logo'),
    path('boards/users/search/', community.user_search, name='board_user_search'),
    path('boards/', community.index, name='board_index'),
    path('boards/new/', community.settings, name='board_create'),
    path('boards/<uuid:board_id>/', community.listing, name='board_list'),
    path('boards/<slug:slug>/', community.listing_by_slug, name='board_public'),
    path('boards/<uuid:board_id>/settings/', community.settings, name='board_settings'),
    path('boards/<uuid:board_id>/taxonomy/', community.taxonomy, name='board_taxonomy'),
    path('boards/<uuid:board_id>/delete/', community.board_delete, name='board_delete'),
    path('boards/<uuid:board_id>/new/', community.edit_post, name='board_post_create'),
    path('boards/<uuid:board_id>/posts/<uuid:post_id>/', community.detail, name='board_post'),
    path('boards/<uuid:board_id>/posts/<uuid:post_id>/edit/', community.edit_post, name='board_post_edit'),
    path('boards/<uuid:board_id>/posts/<uuid:post_id>/delete/', community.post_delete, name='board_post_delete'),
    path('boards/<uuid:board_id>/posts/<uuid:post_id>/status/', community.change_status, name='board_post_status'),
    path('boards/<uuid:board_id>/posts/<uuid:post_id>/replies/<uuid:reply_id>/', community.reply_edit, name='board_reply_edit'),
    path("reports/<uuid:report_id>/shares/", sharing.shares, name="report_shares"),
    path("reports/<uuid:report_id>/cover/", views.report_cover, name="report_cover"),
    path("reports/<uuid:report_id>/delete/", views.report_delete, name="report_delete"),
    path("api/reports/<uuid:report_id>/infographic-data/", views.infographic_data_api),
    path("shared/<str:token>/", sharing.public_report, name="public_report"),
    path("connections/google/oauth/", google_oauth.setup, name="google_oauth_setup"),
    path("connections/google/callback/", google_oauth.callback, name="google_oauth_callback"),
    path("connections/<uuid:connection_id>/google/start/", google_oauth.start, name="google_oauth_start"),
    path("connections/<uuid:connection_id>/google/disconnect/", google_oauth.disconnect, name="google_oauth_disconnect"),
    path("connections/<uuid:connection_id>/edit/", views.connection_update, name="connection_update"),
    path("connections/<uuid:connection_id>/delete/", views.connection_delete, name="connection_delete"),
    path("", views.dashboard, name="dashboard"),
    path("reports/", views.library, name="library"),
    path("reports/demo/", views.ensure_demo, name="ensure_demo"),
    path("reports/<uuid:report_id>/design/", views.designer, name="designer"),
    path("reports/<uuid:report_id>/", views.viewer, name="viewer"),
    path("reports/<uuid:report_id>/statistics/", analytics_views.statistics_view, name="statistics"),
    path("reports/<uuid:report_id>/statistics/export/<str:format>/", analytics_views.statistics_export, name="statistics_export"),
    path("reports/<uuid:report_id>/export/<str:format>/", views.report_export, name="report_export"),
    path("connections/", views.connections_page, name="connections"),
    path("manual/", views.manual, name="manual"),
    path("assets/<uuid:asset_id>/", views.asset_view, name="asset"),
    path("projects/import/", views.project_import, name="project_import"),
    path("published/<uuid:publication_id>/", views.publication_view, name="publication"),
    path("embed/", views.embed_view, name="embed"),
    path("api/reports/", views.reports_api),
    path("api/reports/<uuid:report_id>/", views.report_api),
    path("api/reports/<uuid:report_id>/bindings/", views.bindings_api),
    path("api/reports/<uuid:report_id>/preview/", views.preview_api),
    path("api/reports/<uuid:report_id>/publish/", views.publish_api),
    path("api/reports/<uuid:report_id>/execute/", views.execute_api),
    path("api/connections/", views.connections_api),
    path("api/connections/<uuid:connection_id>/test/", views.connection_test_api),
    path("api/connections/<uuid:connection_id>/schema/", views.schema_api),
    path("api/assets/", views.asset_api),
    path("api/embed-sessions/", views.embed_session),
]
