from django.urls import path
from . import views, google_oauth, sharing
from . import analytics_views

urlpatterns = [
    path("reports/<uuid:report_id>/shares/", sharing.shares, name="report_shares"),
    path("reports/<uuid:report_id>/cover/", views.report_cover, name="report_cover"),
    path("api/reports/<uuid:report_id>/infographic-data/", views.infographic_data_api),
    path("shared/<str:token>/", sharing.public_report, name="public_report"),
    path("connections/google/oauth/", google_oauth.setup, name="google_oauth_setup"),
    path("connections/google/callback/", google_oauth.callback, name="google_oauth_callback"),
    path("connections/<uuid:connection_id>/google/start/", google_oauth.start, name="google_oauth_start"),
    path("connections/<uuid:connection_id>/google/disconnect/", google_oauth.disconnect, name="google_oauth_disconnect"),
    path("connections/<uuid:connection_id>/edit/", views.connection_update, name="connection_update"),
    path("connections/<uuid:connection_id>/delete/", views.connection_delete, name="connection_delete"),
    path("", views.dashboard, name="dashboard"),
    path("reports/", views.library, name="library"),
    path("reports/demo/", views.ensure_demo, name="ensure_demo"),
    path("reports/<uuid:report_id>/design/", views.designer, name="designer"),
    path("reports/<uuid:report_id>/", views.viewer, name="viewer"),
    path("reports/<uuid:report_id>/statistics/", analytics_views.statistics_view, name="statistics"),
    path("reports/<uuid:report_id>/statistics/export/<str:format>/", analytics_views.statistics_export, name="statistics_export"),
    path("reports/<uuid:report_id>/export/<str:format>/", views.report_export, name="report_export"),
    path("connections/", views.connections_page, name="connections"),
    path("manual/", views.manual, name="manual"),
    path("assets/<uuid:asset_id>/", views.asset_view, name="asset"),
    path("projects/import/", views.project_import, name="project_import"),
    path("published/<uuid:publication_id>/", views.publication_view, name="publication"),
    path("embed/", views.embed_view, name="embed"),
    path("api/reports/", views.reports_api),
    path("api/reports/<uuid:report_id>/", views.report_api),
    path("api/reports/<uuid:report_id>/bindings/", views.bindings_api),
    path("api/reports/<uuid:report_id>/preview/", views.preview_api),
    path("api/reports/<uuid:report_id>/publish/", views.publish_api),
    path("api/reports/<uuid:report_id>/execute/", views.execute_api),
    path("api/connections/", views.connections_api),
    path("api/connections/<uuid:connection_id>/test/", views.connection_test_api),
    path("api/connections/<uuid:connection_id>/schema/", views.schema_api),
    path("api/assets/", views.asset_api),
    path("api/embed-sessions/", views.embed_session),
]
